server:
  port: 8080
  servlet:
    contextPath: /
spring:
  data:
    mongodb:
      user: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      uri: ${MONGODB_URI}
app:
  cors:
    enabled: true
    allowed-headers: '*'
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    allowed-origins: '*'
    exposed-headers: Content-Disposition, Content-Length, Content-Type
  security:
    disabled: false
    publicResourcesUri:
      - /swagger-ui.html**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v3/api-docs.yaml**
  documentation:
    name: Spring Autoconfigure
    version: 0.0.1
